name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4   # ✅ Updated to v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.8.1"
          channel: beta

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Run analyzer
      - name: Analyze project
        run: flutter analyze

      # 5. Run tests
      - name: Run tests
        run: flutter test

      # 6. Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4   # ✅ Updated to v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
