name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"  # Updated to match SDK requirement ^3.8.1
          channel: stable

      # 3. Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # 4. Generate code (for stacked_generator)
      - name: Generate code
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      # 5. Run analyzer
      - name: Analyze project
        run: flutter analyze

      # 6. Run tests
      - name: Run tests
        run: flutter test

      # 7. Build Android APK
      - name: Build APK
        run: flutter build apk --release

      # 8. Upload APK as artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk